### ISSUE TITLE
Custom Style for the Page

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#1]
I have used a generic style from the GH-Pages Generator. But i'd like to see some custom style, more of a mash of nodeschool.io and Hamburg (maybe whites and reds?).

Volunteers?

**Comment by finnp** [comment]
How do you like http://nodeschool.io/berlin ? If you think it looks okay, I could help adapt the theme and give it a Hamburg look. I am originally from the area by the way (Elmshorn, d'oh).

**Comment by greelgorke** [comment]
Its nice, i'd like that, if you are so kind to help us here :)

**Comment by finnp** [comment]
Okay I just pushed a new version: http://nodeschool.io/hamburg/

I like the Speicherstadt feeling. But I think the colors don't match nicely yet. So feel free to update the colors and experiment with it.

**Comment by greelgorke** [comment]
awesome! thank you!

Colors are nice already, but i'll try around a bit when i get time and nothing else to do so far.
