### ISSUE TITLE
promotion material

### ISSUE THREAD

**Issue by afknapping** [nodeschool/hamburg#10]
i am thinking of a tiny promo package that can be used for example by the geekettes, open tech school, digital media women, etc to post a quick update about the event.
- brief explanation what this is about (~5 sentences)
- motivation and explicit warm welcome to join
- date, time, location, requirements, link to ticket
- some nice photos from past events and the hamburg logo illustrations

i will dig around in the existing blog posts etc and give it a go. please share links that might be helpful for this.

**Comment by greelgorke** [comment]
cool! thank you for doing this.

**Comment by afknapping** [comment]
nicely cropped photos (and filtered, yay): http://hackygolucky.com/pdxnode-presents-nodeschool-io/

i asked on twitter if we can use them.

**Comment by afknapping** [comment]
(first draft)

Always wanted to look into programming but didn't know how? Well, the NodeSchool is coming to Hamburg. At this community-organized, non-profit event you can make your first steps in learning Node, which is based on the JavaScript programming language. While every attendee works through the material by themselves, there will be experienced mentors to help you with any questions.

You will of course learn to write your first program (the classic "Hello World") – but more importantly you will get feedback from the mentors, so continuing the lessons at home will get much easier.

Wait a sec? Continue at home? Actually, yes. The NodeSchool material is running as a self-explaining, interactive workshop on your own computer. So you can keep learning all the time.

While having a little experience with JS will get you a head start, it is not _needed_ to start learning Node. Just bring your laptop and start hacking!

The Node community is looking to be diverse and a safe enviroment for everybody. This means there will be a Code of Conduct in place and all mentors and attendees are urged to enforce it.

So, what are you waiting for? Save the date and grab a ticket! We're looking forward to welcome you to the wonderful world of the Node.

**Comment by afknapping** [comment]
We can use the photos. Credit: PDXNode

(https://twitter.com/HackyGoLucky/status/511946725167476737)

**Comment by hackygolucky** [comment]
You rock, Hamburg!

**Comment by greelgorke** [comment]
@filtercake there is a whole bunch of blog posts on past events on http://nodeschool.io/host.html :)

Thank you @hackygolucky ! you rock too :)

**Comment by afknapping** [comment]
hi @hackygolucky and thx! <3

@greelgorke yeah, i skimmed those but found nothing about promotion. and i totally missed the obvious https://ti.to/nodeschool-berlin/jsfest-2014 :D will give it another go tomorrow...

**Comment by afknapping** [comment]
also: having _some_ JS experience is actually a requirement...

**Comment by greelgorke** [comment]
@filtercake the location is that of neteye.de

**Comment by greelgorke** [comment]
@filtercake what about this, anything done?

**Comment by fgnass** [comment]
Here are the photos @oleharland took at NETEYE last Saturday: https://twitter.com/140eyes/status/531746205748195329

**Comment by afknapping** [comment]
sorry, didn't have time to keep working on this. will close for now because of this, apologies :/

**Comment by greelgorke** [comment]
no problem @filtercake, we had enough attendees :)
