### ISSUE TITLE
hamburg-page + tickets

### ISSUE THREAD

**Issue by mdunisch** [nodeschool/hamburg#12]
I updated the nodeschool.io/hamburg (adding the event and link join to a ti.to-page).
I also created a ti.to-Event for our node-school (https://ti.to/nodeschool-hamburg/nodeschool-hamburg).

@greelgorke: I added you as a teammember (google-adress).

One thing before i would like to open the registration-process: How many tickets we should offer? How many places we have at netEye? I propose to offer 150% of the places (for the not-shown-rate)

**Comment by greelgorke** [comment]
@mdunisch thank you, for stating that.

i think 30 ppl would be a nice start, @fgnass what do you think, enough space for that?

**Comment by fgnass** [comment]
I'd say one floor should be enough for 30-40 people. If we exceed this number we should consider opening a second floor (which would be no problem).

**Comment by mdunisch** [comment]
So than I'll put **50** tickets on ti.to (for a few no-showers) and if we see more interests we increase the number after talking to @fgnass.

ok @greelgorke, @fgnass ?

**Comment by fgnass** [comment]
:+1:

**Comment by greelgorke** [comment]
great!

**Comment by mdunisch** [comment]
ok done!

**Comment by mdunisch** [comment]
So @greelgorke, @fgnass  we are almost full (47 at the moment) :smile: . I think we should:
- not offer more tickets because we only have 6 Mentors at the moment
- send a email to all attendees 10 days before, see: https://github.com/nodeschool/hamburg/wiki/Email-(10-days-before-event)

**Comment by mdunisch** [comment]
@greelgorke can you handle the emailing 10 days before? I won't be at the computer at the 29th.

**Comment by greelgorke** [comment]
sure

**Comment by mdunisch** [comment]
@greelgorke Have you sent the email yesterday?

**Comment by greelgorke** [comment]
i did now :D, yesterday was a full-packed day
