### ISSUE TITLE
Ticket summary

### ISSUE THREAD

**Issue by mdunisch** [nodeschool/hamburg#13]
(I'll update this from time to time)

Mentors: 6
Attendes: 50 -sold out-

Keep on promotion our nodeschool! :yum:

**Comment by ghost** [comment]
I just announced the event in the betahaus and Hamburg Startups facebook groups a thew minutes ago.

**Comment by greelgorke** [comment]
I did 
- the twitter thing, 
- mailed to Diana of Geekettes
- updated the corresponding node.hh event on meetup.

i also have extended the informations on tito with a few more explanations and added the CoC hint.

**Comment by mdunisch** [comment]
I'm happy to see that we are on a good way with the tickets - thank you all for promoting! :+1:
