### ISSUE TITLE
Catering

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#14]
We need a bit of catering. Some snacks etc. enough for a lunch. Here i need some suggestions, where i can ask for an offering.

Ideas?

**Comment by mdunisch** [comment]
http://www.ohitsfresh.de/
Had multiple events where they to the catering and it was always great - but I don't know how expensive this was.

**Comment by fgnass** [comment]
http://www.mikkels.de/catering/

**Comment by ghost** [comment]
I’ve made some got experiences with
http://www.eatclever.de/=

**Comment by fgnass** [comment]
Awesome coffee:
http://www.publiccoffeeroasters.com/leistungen/
http://blackdelight.de/catering.html

**Comment by greelgorke** [comment]
ordered by ohitsfresh, for 60 persons.
