### ISSUE TITLE
idea: nodeschool on 2015-02-08

### ISSUE THREAD

**Issue by robertkowalski** [nodeschool/hamburg#16]
Hi there,

the last nodeschool was really fun and I am looking forward to the next one.

We are having a CouchDB Day on Saturday, the 7th of February in Hamburg. There will be some folks from Germany and the EU being in Hamburg for the weekend. 

Inspired from the nodeschool after this years JSConf EU on Monday as part of the JSFest (http://jsfest.berlin/) I wanted to ask if there is interest in doing a nodeschool on Sunday. We would help to spread the word on our website, attendee-emails and social networks and would be able to have a full weekend of fun learning in Hamburg!

**Comment by finnp** [comment]
Sounds like a good idea :+1:

**Comment by robertkowalski** [comment]
Here is the url to our event (forgot that to mention): http://day.couchdb.org/

**Comment by andywenk** [comment]
awesome :) Thanks !!!

**Comment by greelgorke** [comment]
Yeah, will be great!

**Comment by greelgorke** [comment]
see #18
