### ISSUE TITLE
Node School Event in February 2015

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#18]
This is the main Orga thread. As @robertkowalski suggested in #16 we'll create a fest-type event series, and NodeSchool will take place. Now, we will do some orga stuff.
- [x] schedule the event: 08 Feb 2015
- [x] contact some possible sponsors
  - Interone: Location, Drinks
  - codecentric: Food
- [x] find the location (Interone, Zirkusweg 1 (Atlantikhaus), 19 Floor)
- [x] advertise the event
- [x] find some Mentors

**Comment by robertkowalski** [comment]
whooohoo! what do you think, when is the best time to put the date on our homepage and fire up twitter?

**Comment by greelgorke** [comment]
@robertkowalski i think we already can start to advertise. i think i'd get a room easily for that. food and drinks are another thing, if we get some sponsor there, that would be great.

**Comment by robertkowalski** [comment]
We would need a link target, I started to add a date to the nodeschool-hamburg website, having a location and a ticket link would be cool.

**Comment by robertkowalski** [comment]
happy new year! we would love to start advertising the event, but we still need a location and an updated nodeschool website, any news regarding that?

**Comment by greelgorke** [comment]
i probably got a room already, just need to verify. then we need a sponsor for beverages and mentorZ

**Comment by greelgorke** [comment]
Location: Interone, Zirkusweg 1 (Atlantikhaus), 19 Floor

**Comment by robertkowalski** [comment]
updated the location for the tito site!

**Comment by greelgorke** [comment]
we schould meet once and talk about the organisation. i'm pretty sure, i wont be there on 8th. i've got too much to do around that day and would rather use the sunday for family. But still i'd do the things needed to organize, just need someone to take over the hat at day. @robertkowalski @fgnass what about you guys?

**Comment by fgnass** [comment]
I'll be there. I'd like to talk about the pre-school event for the total beginners. My impression was that the javascripting workshopper was not ready for prime-time yet and was quite frustrating for a lot of attendees. [Codeacademy](http://www.codecademy.com/tracks/javascript) for example provides a much better learning experience for non-programmers. It would be cool if there was a version of javascripting that used https://www.npmjs.com/package/adventure-time to run in the browser and was didactically more like http://jsforcats.com/ – until such a thing becomes reality I'm really unsure if the existing workshopper is the right tool for total newbies. I think that for a pre-school event a classic class environment with one teacher in front is better suited, unless of course you have at least a 1:2 mentor:student ratio.

**Comment by greelgorke** [comment]
@fgnass @robertkowalski i'd like to meet you next week either on monday or friday. lets do lunch together and talk about it.

**Comment by robertkowalski** [comment]
Hi Gregor,

sadly I don't have time tomorrow.

I am quite busy currently because of the JS Unconf and CouchDB Day. I think
I am not going to make it to the nodeschool event in February, but will
continue to help you with all the preparations.

Do you have anything specific that' missing for the event where I can help?

**Comment by fgnass** [comment]
Meeting for lunch on Friday would work for me. Schanzenviertel at 13:00?

**Comment by greelgorke** [comment]
@robertkowalski i can't be at the nodeschool also, but i though you will. well then it's a bit off to involve you with the stuff ;) 

@fgnass lets meet then.

@codingCookie are you there at nodeschool?

**Comment by mdunisch** [comment]
All Ticket are sold right now. Do we have enough mentors?

**Comment by greelgorke** [comment]
not really. if you can get some, go on. we need a few more

**Comment by robertkowalski** [comment]
https://twitter.com/robinson_k/status/560573115948756993

**Comment by greelgorke** [comment]
sponsoring is complete
