### ISSUE TITLE
Idea: NodeSchool Office Hours

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#19]
weekly or every two weeks
1 or 2 mentors
public location
1-2 hours
no ticketing or pre-orga
everyone is invited to come

if you have a question or just want to hangout and go through a workshopper come and do it.

the only thing guaranteed is that there will be a Mentor at the place.

what do you think @nodeschool/hamburg-mentors

**Comment by usefulthink** [comment]
to me that would depend a bit on the location and things i can do if nobody shows up.
But it's a really neat idea and I'd love to see if this concept works.

**Comment by greelgorke** [comment]
the location would pretty much depend on the mentor. basically this would go like:

me as mentor announce that i'll be at 18-19:30 in Schanzenstern St.Pauli and drink my Tee there. Anybody can join me there then.

Of course this would be announce properly and in advance, may be a week before or something.

**Comment by greelgorke** [comment]
anyone else from @nodeschool/hamburg ?

**Comment by robertkowalski** [comment]
Yes, if at least one person joins me for the evening (tweet me at @robinson_k one week in advance or post another way to communicate here)

**Comment by greelgorke** [comment]
i just started. it should be just an issue per hour with location and time, marked with the label. see #24
