### ISSUE TITLE
Mentors wanted: nodeschool on the 8th February 2015

### ISSUE THREAD

**Issue by robertkowalski** [nodeschool/hamburg#21]
There will be a nodeschool again and we are looking for mentors!

I was a mentor last time and it was mindblowing! I can really suggest mentoring to anyone, so many nice folks and such a warm & fuzzy feeling in the evening I went home. 

Who's joining?

**Comment by fgnass** [comment]
I'm in.

**Comment by mdunisch** [comment]
Me too. 
I can set up the ti.to Ticket system again

**Comment by greelgorke** [comment]
@mdunisch already done :)

for me, i'm not sure if i'll be able to be there. but shouldn't be much of a problem
