### ISSUE TITLE
Office Hour Announcement

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#24]
My Office Hour will be at

wednesday 1. April 17-18 o'clock in [Campus Suite Gänsemarkt](https://www.google.de/maps/place/Campus+Suite+-+Valentinskamp/@53.5556748,9.986655,20z/data=!4m2!3m1!1s0x0000000000000000:0xad3a5a9fe0052c1d)

**Comment by robertkowalski** [comment]
awesome! sadly i am quite busy this & next month... can you post a short summary how it went? thank you <3
