### ISSUE TITLE
JSUnconf Nodeschool Anyone?

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#25]
The JSUnconf is on the horizon, so probably it would be nice to do a nodeschool then. i know about the js code retreat on friday before the event. so any suggestions @nodeschool/hamburg-mentors ?

**Comment by robertkowalski** [comment]
I can help regarding promo :)

**Comment by robertkowalski** [comment]
sorry for not mentoring again, but i am organizing the unconf

**Comment by finnp** [comment]
I don't have a ticket yet. But I wanted to come to Hamburg for it. Would be nice to have a nodeschool.

**Comment by finnp** [comment]
Okay I am in. I would prefer Fri-Sun as a date, but maybe I can also arrange Thursday or Monday. Not sure yet.

**Comment by greelgorke** [comment]
screw it, i can't do it this time
