### ISSUE TITLE
Mentors: please RSVP for May 23

### ISSUE THREAD

**Issue by afknapping** [nodeschool/hamburg#30]
Hi @nodeschool/hamburg!

If you can mentor on
- Saturday May 23
- 11:00 to 15:00

please answer in this thread with **yes**. If you want to mentor but are unsure yet if you can make it, please answer with **maybe**.

---

**Looking for info what mentoring actually means?** => See http://nodeschool.io/mentor-at-event.html

---
- The event will take please in the area of [Altona/Bahrenfeld](https://www.google.de/maps/place/Jimdo+GmbH/@53.564614,9.920362,17z/data=!3m1!4b1!4m2!3m1!1s0x47b185eb47b2ae9d:0x6e5e8e48e002b210?hl=de)
- For those interested, there will be [soccer watching](http://www.weltfussball.de/spielplan/bundesliga-2014-2015/) on the beamer afterwards :)

**Comment by herzi** [comment]
yes

**Comment by robin-drexler** [comment]
yes

**Comment by chieftecho** [comment]
yes

Am 01.05.15 um 16:16 schrieb filtercake:

> Hi @nodeschool/hamburg https://github.com/orgs/nodeschool/teams/hamburg!
> 
> If you can mentor on
> - Saturday May 23
> - 11:00 to 15:00
> 
> please answer in this thread with _yes_.
> 
> If you want to mentor but are unsure yet if you can make it, please 
> answer with _maybe_.
> 
> The event will take please in the area of Altona/Bahrenfeld 
> https://www.google.de/maps/place/Jimdo+GmbH/@53.564614,9.920362,17z/data=%213m1%214b1%214m2%213m1%211s0x47b185eb47b2ae9d:0x6e5e8e48e002b210?hl=de
> 
> For those interested, there will be soccer watching 
> http://www.weltfussball.de/spielplan/bundesliga-2014-2015/ on the 
> beamer afterwards :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/nodeschool/hamburg/issues/30.

## 

Viele Grüße,

   Yildirim

**Comment by x3ro** [comment]
yes

**Comment by bruderstein** [comment]
yes!

**Comment by skrings** [comment]
~~maybe~~ yes

**Comment by salzig** [comment]
yes

**Comment by afknapping** [comment]
hey all, awesome you're helping out! :)

please click a mentor ticket at https://ti.to/nodeschool-hamburg/international-day

and it would be nice if you could help spread the word: https://github.com/nodeschool/hamburg/issues/27#issuecomment-101631960
