### ISSUE TITLE
NodeSchool In April around JSUnconfEU

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#33]
So lets do this again on April. Though the Unconf is on weekend i'm thinking about Fryday before that, or a Weekend before or after that

Suggestions?

**Comment by afknapping** [comment]
+1 for friday (evening) before unconf

Can ask if jimdo can sponsor location unless another is in place already...

**Comment by bruderstein** [comment]
It would be good to do it really close, like the Friday, such that people visiting could join in. Just need to coordinate with @zaubernerd if there's going to be a code retreat on the same day.

**Comment by sebs** [comment]
I heard something and would help hosting that or even kickstarting another thing along side.
