### ISSUE TITLE
Is there an additional event planned?

### ISSUE THREAD

**Issue by matthrz** [nodeschool/hamburg#34]
Hello everyone,
I recently got into programming JavaScript (and NodeJS) as a hobby and stumbled upon Nodeschool. Are there any plans for an event in 2017? Is the Hamburg chapter still alive? I'm willing to help.

**Comment by sebs** [comment]
We could hold another all javascript "Coderetreat" if you like. We can do that one or two days. It's about time we do that again

**Comment by matthrz** [comment]
Sounds good. I think one day would be enough for a (re-)start. 
Unfortunately I'm too much of a beginner myself in order to mentor anyone. 
But maybe I can help in some other way. Is there anyone else interested in 
a new edition of the event?

**Comment by sebs** [comment]
I am sure, we will get a full one.  I already opened a ticket and pinged some of the usual suspects.
