### ISSUE TITLE
Sponsoring!

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#6]
# The first event got some love from Sponsors

Following things got sponsorship:
- [x] Location + WiFi by [NETEYE](http://www.neteye.de/)
- [x] Snacks by [codecentric](http://www.codecentric.de)

A Sponsor gets this perks:
- we promote the Sponsor on the event page and gh readme and the public issues with the tag "Sponsored by"
- the sponsor can place posters, give-aways and info material at the event location
## Special Sponsorship

You can sponsor a prominent mentor. Expenses as travel and hotel are here in place. If you have interest in this, reach out to me at we talk about, who could it be and how we can add value for you here.

_this post is a sub-task of #2 for sponsorship stuff_

**Comment by afknapping** [comment]
i could ask at commerce plus (but sb else would have to do the actual orga stuff then, sorry). we did github from scratch there, was the _perfect_ location for rhis kind of thing.

Would not go with a location that doesn't bring Wifi too, too much overhead.

And as mentioned in the other ticket, don't do catering. too much hassle.

prominent mentor has very little (no?) value for attendees :)

**Comment by greelgorke** [comment]
i'm meeting with a potential location sponsor (first come first served), but it's good to have a few options for sure.

About WiFi: this is ideal, when the location has good wifi already. but [this](http://hackygolucky.com/pdxnode-presents-nodeschool-io/) could happen too, and wifi just doesn't handle it right.

About workstations: i expect, that the attenders bring their own machines. however, it's possible to have ppl, who don't posses a notebook. rare this days but possible. Though i havent asked for any. i'll talk to the sponsor today

About Prominent Mentors: i have no idea, how much value this have. It's an idea worth trying, for sure.

**Comment by usefulthink** [comment]
@filtercake already thought of them as well. Since I know everyone there (I have worked there for around 10 years) I could take care of asking them.

**Comment by greelgorke** [comment]
Neteye will host the first event :) Thank you @fgnass for making contact. Really a nice location imo

**Comment by afknapping** [comment]
@greelgorke @fgnass awesome :+1: 

@usefulthink +1, maybe for the second event then...

**Comment by mdunisch** [comment]
@greelgorke should i add the 2 sponsors to the Event-Page and ti.to?

**Comment by fgnass** [comment]
@mdunisch could you change `NetEye` and `Neteye` on the ti.to page into `NETEYE`?

In case you need a logo, here is ours:

![neteye_logo_pos_black](https://cloud.githubusercontent.com/assets/89450/4625768/44ef5680-537a-11e4-8571-4ec8c22fae81.png)
![neteye_logo_pos_rgb](https://cloud.githubusercontent.com/assets/89450/4625770/49873230-537a-11e4-9d34-4bceee958e7d.png)

**Comment by mdunisch** [comment]
@fgnass 
Thank you - I updated the typo and removed the googlemaps on the bottom of the page - it was impossible for me to drop the ping right so the address on the top is better ;-)

I take care of the implementation of the sponsors this week, @greelgorke can you send me a logo of codecentric?

**Comment by greelgorke** [comment]
i added the sponsors yesterday, but without logos, so go ahead and make it better than i did :)
for codecentric log you can use this http://www.codetalks.de/wp-content/uploads/2014/07/Logo_codecentric-1024x169.png

**Comment by mdunisch** [comment]
I inserted the logos and updated the event description (adding german)

**Comment by fgnass** [comment]
There's a typo on the ti.to page: `s/Snacks is sponsored/Snacks are sponsored/`

**Comment by mdunisch** [comment]
thank you @fgnass - fixed :-)
