### ISSUE TITLE
Mentors Wanted!

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#7]
Hello Node.js pros!

You know Node.js? You wanna help others to become a Node.js developer? You are right here!

Put your name here and we create some awesome Node.js learning time!

_this post is a sub-task of #2 for mentors searching_

**Comment by robertkowalski** [comment]
Robert Kowalski

**Comment by mdunisch** [comment]
Martin Dunisch

**Comment by greelgorke** [comment]
Gregor Elke, duh

**Comment by finnp** [comment]
Finn Pauls

**Comment by fgnass** [comment]
Felix Gnass

**Comment by greelgorke** [comment]
@fgnass nice, i invited you to the team :+1:

**Comment by usefulthink** [comment]
Count me in!

**Comment by greelgorke** [comment]
tap! you're in!

**Comment by mdunisch** [comment]
@greelgorke, @finnp, @fgnass, @usefulthink, @robertkowalski 
Now that we have a date: Please confirm that you can attend.

For that: at https://ti.to/nodeschool-hamburg/nodeschool-hamburg we have a ticket-category "NodeJS Mentor" - please take a ticket so we have your contact-details!

**Comment by greelgorke** [comment]
@ Mentors: everyone, who will be there: please look in to the courses, play a bit with them. Also there is the new [js beginner course](https://github.com/sethvincent/javascripting), i think we will use at the event.

**Comment by greelgorke** [comment]
We also certainly should have at least one Mentor who's experienced with the setup on a Windows machine (i know, most of us are using mac or linux right?)

**Comment by robertkowalski** [comment]
I got a nice tip from @wraithan from PDX who has mentored alot that I want to share and also propose: folks that need help should try to ask their neighbor first. Just if that does not help, they should raise their hand for a mentor. This way we can help a lot of people with the relatively small amount of mentors.

Let's try lazy consensus regarding that: you don't need to reply if you think it is a good idea

**Comment by wraithan** [comment]
We've found that this really solidifies the lesson in people as well. And they feel empowered to work together on problems instead of feeling like they have to solve everything themselves. Basically we are teaching them to pair program without using that (slightly buzzword-y) word. Happy to discuss this if anyone has questions.

**Comment by greelgorke** [comment]
this is a good idea, and i thought about it already too. this is the same experience from learning groups at universities, and the work quite well there. i will definitely encourage this on Saturday

**Comment by greelgorke** [comment]
Thanks everybody! it was a nice Event
