### ISSUE TITLE
Schedule first Event in Hamburg - Doodle

### ISSUE THREAD

**Issue by greelgorke** [nodeschool/hamburg#8]
here is the [doodle](http://doodle.com/w6dzuhg59nz8nzqg)

Please put yourself in ;)

**Comment by finnp** [comment]
Do we have a date? Looks like November 1 works for everybody until now.

**Comment by greelgorke** [comment]
i have to check it for myself. 50% of my saturdays are used up already

**Comment by mdunisch** [comment]
@greelgorke: So what about the 1st november? Did you check if we can use the rooms of NetEYE at this date?

**Comment by greelgorke** [comment]
we can.

but i'd like to wait with closing the doodle till friday

**Comment by greelgorke** [comment]
Looks like it's the 1.11.

Before i close this issue, one detail is to get cleared there: the time. I thought about this options:
- 10-17 (7h)
- 13-18 (5h)
- 13-20 (7h)

it's Saturday, so i don't expect anyone earlier than 10, even that may be a bit too early i guess.

**Comment by mdunisch** [comment]
13-18 (5h) :+1:

**Comment by fgnass** [comment]
13-18 (5h) :+1:

**Comment by codingCookie** [comment]
10-17 (7h) :+1: 

I think 10 isn´t too early....maybe start at 10h with the "welcome and arriving"-stuff start with official welcome and introduction etc at 11h and end by 18h....maybe?

**Comment by robertkowalski** [comment]
13-18 (5h)

**Comment by finnp** [comment]
13-18 (5h) :yum:

**Comment by ghost** [comment]
10-17 (7) :+1:

**Comment by afknapping** [comment]
13-18 (5h) :+1:

**Comment by greelgorke** [comment]
ok, i see. here's the idea: 

let's do it in two parts, the main track and the pre-track. 

The main track will be 13-18 and be workshopping. 

before that, starting by 12 (or even at 11?) we will run a small crash course into javascript and cli basics. As i read in other discussions, there may be attenders, who's not familiar with JS or a the terminal, and need some advice here first. 

How is that? this is the last point i want to decide (till tomorrow eve) so we can start promoting it from the Saturday on.

**Comment by greelgorke** [comment]
silence is a sign of acceptance, right? :)

**Comment by fgnass** [comment]
:+1: having a pre-track for beginners is a great idea. Let's do this :)

**Comment by greelgorke** [comment]
fine.
1. November 2014
2. Starting at 11:00 with a crash course in JavaScript and CLI basics.
3. Following with the actual NodeSchool at 13:00 till 18:00

i'll write a something for the website, then we can announce it.

**Comment by greelgorke** [comment]
OK I have a problem. I definitely can't be there on the 1. November. We have two options: Either we move it a week further to the 8.11.  or somebody of you have to step up and take the "field moderator" responsibility on this day. I'd prefer the shift, since i really want to be there, but i also would accept the replacement option.

Opinions?

**Comment by ghost** [comment]
+1 for the shift

**Comment by codingCookie** [comment]
i´m very very sad...but i can´t be there on both dates :( 
but i would give +1 for the shift :)

**Comment by fgnass** [comment]
8.11. is fine for me too. Doing the event without you would simply feel wrong ;)

**Comment by mdunisch** [comment]
Oh sorry - I recently filled out the eventform at nodeschool.io and sent the 1.11. - I did't see the topic here. But I'll write a email soon to cancel this submission. 

About the Date: 8.11 is fine for me, too.

@greelgorke: Want we fix this date? It's not very long until the 8.11. and we definitely should start promoting the event!

**Comment by greelgorke** [comment]
yes it is fixed, i cleared that with Neteye.

**8.11. 11-13-18 it is**
