### ISSUE TITLE
Hexagon Logo

### ISSUE THREAD

**Issue by fgnass** [nodeschool/hamburg#9]
My co-worker @oleharland made a hexagon version of the NodeSchool HH logo in the spirit of [this guide](https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker):
![nodeschool-hamburg](https://cloud.githubusercontent.com/assets/89450/4248994/86f9ba40-3a6e-11e4-8164-e4e5791c126d.png)

What do you guys think?

**Comment by finnp** [comment]
Wow, that looks awesome! We should totally make a sticker out of it :)

**Comment by greelgorke** [comment]
cool! do you wanna push it to the repo?

I'll look into the sticker thingy soon. wanna stickers for node.HH too

**Comment by fgnass** [comment]
Here it is: ba21931a178d7c52c53d8f28f2a4239219fd241d

**Comment by greelgorke** [comment]
awesome

**Comment by greelgorke** [comment]
@finnp shall we use this instead of your version? both are nice, but i think this one is a better fit, since most other chapters adapt this design. what do you think?

**Comment by finnp** [comment]
Yeah I mean it certainly looks better, but with it hexagon shape it doesn't fit all purposes. So I am fine with using both. I think it wold be also nice to create a logo similar to mine, but based on this hexagon design more more consistency.

**Comment by greelgorke** [comment]
ah i see, it's supposed to be for stickers. so i'm ok with using both also. your logo is a better fit for banner-like usage

**Comment by fgnass** [comment]
I'm sure @oleharland can make us a rectangular version with a full-width [school house](http://nodeschool.io/images/schoolhouse.svg) but with the Hamburg symbol taken from the hexagon. I'll go ahead and ask him ;)

**Comment by finnp** [comment]
@fgnass Awesomeness!

**Comment by greelgorke** [comment]
:+1:

**Comment by finnp** [comment]
@fgnass One thing: It should be black on transparent like the [original](http://nodeschool.io/images/schoolhouse.svg) :)

**Comment by greelgorke** [comment]
@fgnass i'd like to have the node hexa-n char instead of the cross

**Comment by fgnass** [comment]
Hm, to be consistent with the overall look, the "n" would have to be drawn as hollow shape (i.e. only the outline) but at that scale the stroke would need to be considerably thinner.

Using http://nodejs.org/images/logos/js-black.svg would probably work better, but I guess this wouldn't be in line with Joyent's [trademark policy](http://nodejs.org/images/trademark-policy.pdf). Not using any trademarked symbols at all is probably the best way to go.

Ole showed my one variant with a cross in the middle and hexagons instead of the stars, but we finally decided not mess with any of the religious symbols.

**Comment by greelgorke** [comment]
they are pretty liberal for user groups and open source communities, aren't they?

**Comment by fgnass** [comment]
I guess so :) I just thought that removing the "TM" (by scaling it down to being practically invisible) might be a little crude, especially as the policy explicitly states this as a "DON'T". But I'm with you, adding some more node references would be fun!

I just saw that you'll be at the NETEYE office tomorrow, that's awesome! I'll try to be there too, so I can introduce you to Ole. I'm sure he'll come up with a neat solution (he always does). Looking forward to meet you in person!

**Comment by afknapping** [comment]
<3 the illustration. Suggestion though: Hamburg has The Hamburg Red™ ([#e30613](http://www.hamburg.de/contentblob/9994/thumbnail/headnavigationdesktop-fm.gif) methinks), would be nice to stay with it :)

**Comment by greelgorke** [comment]
lookma https://www.hamburg.de/wappen/

@fgnass we could contact Joyent on that or just let the js out of this, turn the stars to hexagons and the cross to n and let it be.

**Comment by finnp** [comment]
Does anyone of you know where to print those Hexagon stickers in good quality? Because the StickerMule shipping costs to Germany are like 30 Euro. If anyone of you has an idea, we could order a batch of stickers for NodeSchool Berlin and Hamburg.

PS: I started making a list over here: https://github.com/nodeschool/berlin/issues/3

**Comment by greelgorke** [comment]
@finnp @fgnass told me, his logo designer will take care about sticker printing, may be you both chat about it?

**Comment by fgnass** [comment]
Hey guys, I'm currently sick and therefore not in the office, but I'm sure Ole can take care of this. I'll talk to him tomorrow when I'll (hopefully) feel better. Expect an update by the end of the week.

**Comment by fgnass** [comment]
@oleharland is on it. He's getting a quote from http://www.cutandprint.de/ who are super nice and provide awesome quality. How many stickers do we need? 50, 100, 200?

BTW, have you seen https://github.com/terinjokes/StickerConstructorSpec?

**Comment by greelgorke** [comment]
@fgnass @oleharland could you put node.HH stickers with it? i can provide you with an eps for that.

i think 100 ea/per sticker is fine for now.

**Comment by fgnass** [comment]
@greelgorke sure!

**Comment by greelgorke** [comment]
@fgnass can i mail it to you or @oleharland ?

**Comment by fgnass** [comment]
@greelgorke if you send it to `fgnass at gmail com` I'll take care of it.

**Comment by fgnass** [comment]
Woohoo, the stickers are ready! :smile: I guess they'll be in the mail by Monday. I'll post pictures once I have them.

**Comment by greelgorke** [comment]
WOOOOOH

**Comment by greelgorke** [comment]
@fgnass any update on this? :)

**Comment by fgnass** [comment]
We have them here but are neither happy with the colors nor the material. We'll order another batch from a different supplier.

**Comment by greelgorke** [comment]
Stickers are nicely done! thanx!

**Comment by fmoliveira** [comment]
Awesome job @oleharland @fgnass ! Congratulations! :smile:
